### PR TITLE
Prevent user from updating rejected holidays

### PR DESCRIPTION
**Pull request by lee-cheung**
I have prevented user from updating rejected holidays by removing update button and i have also removed warning messages.

screenshot_1539970604

### CODE REVIEW

**Comment by bgribz** [comment]
Hey @lee-cheung can you fix the branch name and reopen plzzzz `feature/TS-124`

**Comment by bgribz** [comment]
Hey @lee-cheung can you fix the branch name and reopen plzzzz `feature/TS-124`

**Comment by bgribz** [comment]
Hey @lee-cheung can you fix the branch name and reopen plzzzz `feature/TS-124`

**Comment by lee-cheung** [comment]
woops, my bad. Yes i will change that

**Pull request closed without merging**
